# espanso match file https://espanso.org/docs/
matches:
  - trigger: "//date"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%F"
    backend: Clipboard
  - trigger: "//day"
    replace: "{{day}}"
    vars:
      - name: day
        type: date
        params:
          format: "%F %a"
  - trigger: "//time"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%F %T"
    backend: Clipboard
  - trigger: "//ts"
    replace: "`{{time}}`"
    vars:
      - name: time
        type: shell
        params:
          cmd: "date -u +'%F %T %Z'"
    backend: Clipboard
  - trigger: "//md"
    replace: "{{output}}"
    vars:
      - name: clipboard
        type: clipboard
      - name: output
        type: shell
        params:
          cmd: "gh md link '{{clipboard}}'"
    backend: Clipboard
    preserve_clipboard: true
  - trigger: "//ml"
    replace: "{{output}}"
    vars:
      - name: clipboard
        type: clipboard
      - name: output
        type: shell
        params:
          cmd: "gh md link --simple '{{clipboard}}'"
    backend: Clipboard
    preserve_clipboard: false
  - trigger: "//ir"
    replace: "{{output}}"
    vars:
      - name: clipboard
        type: clipboard
      - name: output
        type: shell
        params:
          cmd: "gh md ref '{{clipboard}}'"
    backend: Clipboard
    preserve_clipboard: false
  - trigger: "aqq"
    replace: "aqueduct"
